version: '3'

services:
    traefik-proxy:
        image: traefik:latest
        container_name: traefik-proxy
        restart: always
        command: --api.insecure=true --providers.docker
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config:/etc/traefik/
            - ./acme:/etc/traefik/acme