global:
  checkNewVersion: true
  sendAnonymousUsage: true
log:
  level: "ERROR"
  format: "common"
  filePath: "/var/log/traefik/traefik.log"
api:
  dashboard: true
  insecure: true
  debug: false
ping:
  entryPoint: traefik
entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: Host(`{{ normalize .Name }}.docker.localhost`)